services:
  app:
    build: .
    volumes:
      - .:server_django
    ports:
      - 8000:8000
    image: app:server_django
    container_name: server_django_container
    command: python manage.py runserver 0.0.0.0:8000
